version: '3'

services:

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    ports: 
      - "${DB_PORT}:3306"
  
  app:
    container_name: social-music-app
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
        SECRET_KEY: "${SECRET_KEY}"
        DB_NAME: "${DB_NAME}"
        DB_USER: "${DB_USER}"
        DB_PASSWORD: "${DB_PASSWORD}"
        DB_HOST: "${DB_HOST}"
        DB_PORT: '${DB_PORT}'
        MUSIXMATCH_API: "${MUSIXMATCH_API}"
    volumes:
     - .:/app_data