# Generated by Django 4.1.7 on 2023-02-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_tracks_authors_remove_tracks_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='reliased',
            field=models.DateField(default=''),
        ),
    ]
