# Generated by Django 4.1.7 on 2023-02-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_albums_reliased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='reliased',
            field=models.DateField(null=True),
        ),
    ]
