# Generated by Django 4.1.7 on 2023-02-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_albums_reliased'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Artists',
        ),
    ]
