# Generated by Django 4.1.7 on 2023-03-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_following'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlists',
            unique_together={('name', 'creator')},
        ),
    ]
