# Generated by Django 4.1.7 on 2023-02-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_tracks_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlists',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
