# Generated by Django 4.1.7 on 2023-02-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='added_playlists',
            field=models.ManyToManyField(through='app.UserHasPlaylists', to='app.playlists'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='added_tracks',
            field=models.ManyToManyField(through='app.UserHasTracks', to='app.tracks'),
        ),
    ]
